Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -21,7 +21,7 @@ jobs:
         run: echo "test=hello" >> "$GITHUB_OUTPUT"
       - id: step2
         run: |
-          echo -e "qwq\nqwq\nawa\nawa" | sed 's/^/test=/' | tee -a "$GITHUB_OUTPUT"
+          noop || (echo "test=Failed" >> "$GITHUB_OUTPUT" && exit 1)
   job2:
     runs-on: ubuntu-latest
     needs: job1
@@ -30,3 +30,11 @@ jobs:
           OUTPUT1: ${{needs.job1.outputs.output1}}
           OUTPUT2: ${{needs.job1.outputs.output2}}
         run: echo "$OUTPUT1 $OUTPUT2"
+
+  job3:
+    runs-on: ubuntu-latest
+    needs: job1
+    if: ${{needs.job1.outputs.output2 == 'Failed'}}
+    steps:
+      - name: test
+        run: echo test
